// <auto-generated />
using System;
using AgeOfChess.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgeOfChess.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlackEloAtGame")
                        .HasColumnType("int");

                    b.Property<int?>("BlackEloDelta")
                        .HasColumnType("int");

                    b.Property<string>("BlackPlayerToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("BlackStartingGold")
                        .HasColumnType("int");

                    b.Property<int?>("BlackTimeMsRemaining")
                        .HasColumnType("int");

                    b.Property<int?>("BlackUserId")
                        .HasColumnType("int");

                    b.Property<int>("BoardSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LobbyId")
                        .HasColumnType("int");

                    b.Property<string>("MapSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<string>("MovesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("TimeControlEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TimeIncrementSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteEloAtGame")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteEloDelta")
                        .HasColumnType("int");

                    b.Property<string>("WhitePlayerToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("WhiteTimeMsRemaining")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerToken")
                        .IsUnique();

                    b.HasIndex("BlackUserId");

                    b.HasIndex("LobbyId")
                        .IsUnique();

                    b.HasIndex("WhitePlayerToken")
                        .IsUnique();

                    b.HasIndex("WhiteUserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.HistoricGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlackBid")
                        .HasColumnType("int");

                    b.Property<int?>("BlackEloAtGame")
                        .HasColumnType("int");

                    b.Property<int?>("BlackEloDelta")
                        .HasColumnType("int");

                    b.Property<int?>("BlackPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("BoardSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MapSeed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MoveCount")
                        .HasColumnType("int");

                    b.Property<string>("MovesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("TimeControlEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TimeIncrementSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteBid")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteEloAtGame")
                        .HasColumnType("int");

                    b.Property<int?>("WhiteEloDelta")
                        .HasColumnType("int");

                    b.Property<int?>("WhitePlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HistoricGames");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<int>("HostUserId")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlitzGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("BulletGamesPlayed")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("EloBlitz")
                        .HasColumnType("int");

                    b.Property<int>("EloBullet")
                        .HasColumnType("int");

                    b.Property<int>("EloRapid")
                        .HasColumnType("int");

                    b.Property<int>("EloSlow")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("GoogleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<int>("RapidGamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("SlowGamesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.GameSession", b =>
                {
                    b.HasOne("AgeOfChess.Server.Data.Models.User", "BlackUser")
                        .WithMany()
                        .HasForeignKey("BlackUserId");

                    b.HasOne("AgeOfChess.Server.Data.Models.Lobby", "Lobby")
                        .WithOne("GameSession")
                        .HasForeignKey("AgeOfChess.Server.Data.Models.GameSession", "LobbyId");

                    b.HasOne("AgeOfChess.Server.Data.Models.User", "WhiteUser")
                        .WithMany()
                        .HasForeignKey("WhiteUserId");

                    b.Navigation("BlackUser");

                    b.Navigation("Lobby");

                    b.Navigation("WhiteUser");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.Lobby", b =>
                {
                    b.HasOne("AgeOfChess.Server.Data.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("AgeOfChess.Server.Data.Models.Lobby", b =>
                {
                    b.Navigation("GameSession");
                });
#pragma warning restore 612, 618
        }
    }
}
